version: "3"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    # volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgresql://root:root@postgres:5432/tasks_db
